version: '3.8'

services:
  redis:
    build: .
    container_name: creator-platform-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - creator-platform

  redis-cluster:
    profiles: ["cluster"]
    build: .
    container_name: creator-platform-redis-cluster
    ports:
      - "7000-7005:7000-7005"
      - "17000-17005:17000-17005"
    volumes:
      - redis_cluster_data:/data
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      - REDIS_CLUSTER_ENABLED=yes
    restart: unless-stopped
    networks:
      - creator-platform

volumes:
  redis_data:
    driver: local
  redis_cluster_data:
    driver: local

networks:
  creator-platform:
    driver: bridge